Add mssql_role to manipulate role of a SQL Server.
betr-io/terraform-provider-mssql pull request #51
Opened 2022-12-14 16:15 UTC by paulbrittain

Hello, I hope this PR finds you well.

The objective of this PR is primarily to add a new resource mssql_role for manipulating SQL Server Roles.

Other changes include

- Bumping dependency versions for the examples
- kreuzwerker is now the source for the docker provider https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs
- Added the ability to debug the provider by passing a -debug flag parameter.
- Removed some unused code, such as in the function testAccImportStateId, now renamed to testResourceTryGetStateId
- Tests added
- Documentation added, changelog updated, and version bumped.

Note: I've tried to run the acceptance tests against Azure AD with no success. Further attempts are ongoing but the issue is likely related to Azure Firewall rules. Acceptance tests pass locally. I can provide an update here if progress is made.

![image](https://user-images.githubusercontent.com/7349615/207649166-2f7d433c-dafd-4df5-9f79-52319a87c64a.png)

If none is possible, can the acceptance tests be ran + verified by an existing pipeline or by a maintainer?

PS. The changelog needs to be updated with the diff link for the proposed minor verson bump when it's available.

Many thanks

2022-12-14 16:18 UTC, alxy commented on docs/resources/role.md
> +* `role_name` - (Required) The name of the roler. Changing this resource property modifies the existing resource.
```suggestion
* `role_name` - (Required) The name of the role. Changing this resource property modifies the existing resource.
```

2022-12-14 16:18 UTC, alxy commented on docs/resources/role.md
> +terraform import mssql_role.example 'mssql://example-sql-server.database.windows.net/master/user@example.com'
Looks odd, shouldnt there be the role name?

2022-12-14 16:22 UTC, alxy commented on sql/role.go
> +  SET @sql = 'CREATE ROLE ' + QuoteName(@roleName);
I think one potential improvement here could be to also support [authorization](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-role-transact-sql?view=sql-server-ver16#arguments). But that can probably be added in another PR:
`CREATE ROLE role_name [ AUTHORIZATION owner_name ]  `

2022-12-14 16:23 UTC, alxy commented on test-fixtures/all/variables.tf
> +
This is odd, you need this variable only to run the local tests, where the sql server is started in the Docker container. Is there no better fix for this?

2022-12-14 16:29 UTC, paulbrittain commented on docs/resources/role.md
> +* `role_name` - (Required) The name of the roler. Changing this resource property modifies the existing resource.
Fixed

2023-08-21 08:19 UTC, BasLangenberg commented
Hi - Is there any chance this will be merged and pushed to the TF registry? We are having a need for this functionality at work as well. :-)

Thanks!

2024-03-27 11:00 UTC, magne requested changes
- All the import acceptance tests (TestAccLogin_Local_BasicImport, Test_resourceRoleImport, and TestAccUser_Local_Import) fail.
- The PR should be merged with master to bring it up to date.

2026-08-01 17:25 UTC, closed without merging